version : 3.10.6
services:
 django:
  image: django-docker:0.0.1
  build : .
  ports :
   - "8000:8000"

  depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sooraj@pass1
      - POSTGRES_DB=ongomain

volumes:
  postgres_data:



# version: '3.10.6'

# services:
#   postgres:
#     image: postgres:13.1
#     healthcheck:
#       test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
#       timeout: 45s
#       interval: 10s
#       retries: 10
#     restart: always
#     environment:
#       - POSTGRES_USER=root
#       - POSTGRES_PASSWORD=Sooraj@pass1
#       - APP_DB_USER=ongomain
#       - APP_DB_PASS=admin7
#       - APP_DB_NAME=admin7
#     volumes:
#       - ./db:/docker-entrypoint-ongomain.d/
#     ports:
#       - 5432:5432